### ISSUE TITLE
Runtime error in the second stage of code compilation

### ISSUE THREAD

**Issue by pranay1990** [SHI-Labs/Forget-Me-Not#3]
Hi authors, I was recently going through your paper, **Forget-Me-Not: Learning to Forget in Text-to-Image Diffusion Models**, and wanted to replicate the experimental results as state in the paper. To this end, I followed the necessary steps for setup, and thereafter, execute the first on compilation of the code as shown,

> python run.py configs/ti.yaml

Thereafter, on running the second stage of compilation

> python run.py configs/attn.yaml

we encountered the following Runtime Error

`RuntimeError: torch.cat(): expected a non-empty list of Tensor`

Could you please help us in fixing this problem

**Comment by ericlormul** [comment]
the error states that torch.cat operation receives an empty list. You may try trace it back to where the error happens. Probably the concept to-be-forget in text prompt is not detected.

**Comment by ruchikachavhan** [comment]
Hi @pranay1990. How did you solve the issue? I am having the exact same one.
